receivers:
  otlp:
    protocols:
      http:
        endpoint: "0.0.0.0:4318"

processors:
  batch: {}

exporters:
  # Cambiamos "logging" por "debug" para cumplir con la nueva versión
  debug: {}

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [debug] # Actualizado aquí también