services:
  traefik:
    image: traefik:v2.10
    container_name: traefik_gateway
    command:
      - "--api.dashboard=true"
      - "--api.insecure=false"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - red_observabilidad
    labels:
      - "traefik.enable=true"
      - "traefik.http.middlewares.admin-auth.basicauth.users=admin:$$apr1$$PZzjmHUa$$B7hfSnvyEnBj1CXSdeC.80"
      
      # 👑 EL TRUCO MAESTRO: Separamos el panel usando un subdominio falso (admin.localhost)
      - "traefik.http.routers.dashboard.rule=Host(`admin.localhost`)"
      - "traefik.http.routers.dashboard.service=api@internal"
      - "traefik.http.routers.dashboard.middlewares=admin-auth"


networks:
  red_observabilidad:
    external: true